spring:
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: config-server
    instance-id: ${spring.application.name}:${server.port}